// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9sI1muIwAiQF9S5Lp2DOUoHY50ptQfs',
    appId: '1:367197654699:web:edd227998f8f5a792cf1ee',
    messagingSenderId: '367197654699',
    projectId: 'myheartbeat-project',
    authDomain: 'myheartbeat-project.firebaseapp.com',
    storageBucket: 'myheartbeat-project.appspot.com',
    measurementId: 'G-8E29JEWWBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANlMbSxiWl2E8537gL4hHqJudPHVMyVmA',
    appId: '1:367197654699:android:56553f88553a2cac2cf1ee',
    messagingSenderId: '367197654699',
    projectId: 'myheartbeat-project',
    storageBucket: 'myheartbeat-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpO_hErbzHnKStFzLLgmi0xHXeYzsvUdo',
    appId: '1:367197654699:ios:f4b58cad68bfb80e2cf1ee',
    messagingSenderId: '367197654699',
    projectId: 'myheartbeat-project',
    storageBucket: 'myheartbeat-project.appspot.com',
    iosBundleId: 'com.example.myheartbeatProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpO_hErbzHnKStFzLLgmi0xHXeYzsvUdo',
    appId: '1:367197654699:ios:f4b58cad68bfb80e2cf1ee',
    messagingSenderId: '367197654699',
    projectId: 'myheartbeat-project',
    storageBucket: 'myheartbeat-project.appspot.com',
    iosBundleId: 'com.example.myheartbeatProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt9sI1muIwAiQF9S5Lp2DOUoHY50ptQfs',
    appId: '1:367197654699:web:84f56d9a1d7f0bf72cf1ee',
    messagingSenderId: '367197654699',
    projectId: 'myheartbeat-project',
    authDomain: 'myheartbeat-project.firebaseapp.com',
    storageBucket: 'myheartbeat-project.appspot.com',
    measurementId: 'G-DCW0V9TVMJ',
  );
}
